module.exports.expect = [
    { elems: ['head', 'title', 'left', 'right'] },
    { block: 'meta' },
    { block: 'metalink' },
    { block: 'logo' },
    { block: 'menu' },
    { block: 'page' },
    { block: 'container' },
    { block: 'button' },
	{ block: 'border' },
	{ block: 'header' },
	{ block: 'grid' },
	{ block: 'option' },
	{ block: 'content' },
    { block: 'link' },
    { block: 'blog' },
    { block: 'content' },
    { block: 'spacer' },
    { block: 'fluid' },
    { block: 'wrap' },
    { block: 'mini' },
    { block: 'v-menu' },
    { block: 'flex' },
    { block: 'section' }
];
